---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - k8s

- hosts: masters
  gather_facts: true
  become: yes
  roles:
    - k8s-master

- hosts: workers
  become: yes
  roles:
    - k8s-worker